version: "3"

services:
  nginx-extra:
    image: ghcr.io/aasaam/nginx-extra:latest
    container_name: nginx-extra
    hostname: nginx-extra
    network_mode: host
    volumes:
      # http
      - ./conf.d/http:/conf.d/http:ro
      # stream
      - ./conf.d/stream:/conf.d/stream:ro
