name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * FRI'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: |
          sudo apt install jq curl -y
          make
          find nginx -type f -name '.gitignore' -delete

          docker build -t aasaam/nginx-extra .
          docker image inspect aasaam/nginx-extra:latest
          docker push aasaam/nginx-extra
          docker tag aasaam/nginx-extra ghcr.io/aasaam/nginx-extra:latest
          docker push ghcr.io/aasaam/nginx-extra:latest

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: aasaam/nginx-extra
